Repository UBC-MDS/rbccovideda, pull requests merged in 2022-02, with the labels that each got.

#44 Fixes the problems that caused warning and note during check()
  DESCRIPTION
  R/plot_hist_by_cond.R
  R/plot_line_by_date.R
  R/show_summary_stat.r
  tests/testthat/test_plot_hist_by_cond.R
Labels: bug

#63 Feat githubactions
  .github/workflows/R-CMD-check.yaml
  README.Rmd
  README.md
Labels: enhancement

#66 Update README with documentation link
  README.Rmd
  README.md
  docs/articles/index.html
  docs/articles/rbccovideda-vignette.html
  docs/articles/rbccovideda-vignette_files/figure-html/unnamed-chunk-6-1.png
  docs/articles/rbccovideda-vignette_files/figure-html/unnamed-chunk-7-1.png
  docs/articles/rbccovideda-vignette_files/figure-html/unnamed-chunk-8-1.png
  docs/articles/rbccovideda-vignette_files/figure-html/unnamed-chunk-9-1.png
  docs/index.html
  docs/pkgdown.yml
  docs/reference/Rplot002.png
  docs/reference/get_data.html
  docs/reference/index.html
  docs/reference/plot_hist_by_cond-1.png
  docs/reference/plot_hist_by_cond-2.png
  docs/reference/plot_hist_by_cond.html
  docs/reference/plot_line_by_date-1.png
  docs/reference/plot_line_by_date-2.png
  docs/reference/plot_line_by_date.html
  docs/reference/show_summary_stat.html
Labels: documentation
