Repository UBC-MDS/rbccovideda, pull requests merged in 2022-01, with the labels that each got.

#18 Clean up documentation after restructure
  .Rbuildignore
  .github/.gitignore
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  DESCRIPTION
  NAMESPACE
  R/plot_line_by_date.R
  man/getData.Rd
  man/get_data.Rd
  man/plotHistByCond.Rd
  man/plotLineByDate.Rd
  man/plot_line_by_date.Rd
  man/showSummaryStat.Rd
  man/show_summary_stat.Rd
Labels: documentation, enhancement

#17 Added roxygen for plotlinebydate
  R/plot_line_by_date.R
Labels: enhancement

#22 Update return value in doc for show_summary_stat
  R/show_summary_stat.r
  man/show_summary_stat.Rd
Labels: documentation, enhancement

#37 feat: added tests for get_data() and updated location of sample data
  R/get_data.R
  tests/case_data_sample.csv
  tests/testthat.R
  tests/testthat/test-get_data.R
  testthat.R
Labels: enhancement

#38 Added functionality of the plot_line_by_date
  R/plot_line_by_date.R
Labels: enhancement

#39 feat: fixed package referencing in testthat.R to avoid issues with de…
  tests/testthat.R
  tests/testthat/test-get_data.R
Labels: bug, enhancement

#40 Added tests for plot_line_by_date
  DESCRIPTION
  R/plot_line_by_date.R
  man/plot_line_by_date.Rd
  tests/testthat/test-plot_line_by_date.R
Labels: enhancement
